services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "postgres.railway.internal:host-gateway"
    ports:
      - "80:9000"
    environment:
      - YII_DEBUG=false
      - YII_ENV=prod
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
